pin button1 = 12
pin button2 = 10
pin redLED = 2
pin greenLED = 3
pin blueLED = 4

if (readPin button1 == 0) and (readPin button2 == 0) begin
    setPin redLED,low
end

if (not readPin button1 == 0) and (readPin button2 == 0) begin
    setPin redLED,high
end

if (readPin button1 == 0) and (not readPin button2 == 0) begin
    setPin redLED,high
end

if (not readPin button1 == 0) and (not readPin button2 == 0) begin
    setPin redLED,low
end